version: "3"

services:
  db:
    image: mysql:8
    container_name: php-db
    volumes:
      - ./.local/mysql:/var/lib/mysql
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: sample
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    container_name: php-sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
